require:
  - rubocop-airbnb

AllCops:
  Exclude:
    - 'db/**/*'
    - 'docs/*'
    - 'bin/*'
    - 'config/environments/*'
    - 'config/application.rb'
    - 'config/initializers/*'
    - 'config/spring.rb'
    - 'lib/tasks/*'
    - 'vendor/**/*'
    - 'tmp/*'