version: '3'
services:
# =========本番環境ではコメントアウトすること！===========
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: boardgame_match_development
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql # データの永続化
    command: --default-authentication-plugin=mysql_native_password # 認証方式を8系以前のものにする。
    networks:
      - boardgame_match-network
# =================================================

  app:
    build:
      context: .
  # =========ローカルと本番切り替え===========
    # 本番用
    # command: bundle exec puma -C config/puma.rb -e production
    # ローカル用
    command: bundle exec puma -C config/puma.rb
  # ======================================
    volumes:
      - .:/boardgame_match
      - public-data:/boardgame_match/public
      - tmp-data:/boardgame_match/tmp
      - log-data:/boardgame_match/log
    networks:
      - boardgame_match-network

  web:
    build:
      context: containers/nginx
    volumes:
      - public-data:/boardgame_match/public
      - tmp-data:/boardgame_match/tmp
    ports:
      - 80:80
    depends_on:
      - app
    networks:
      - boardgame_match-network

volumes:
  public-data:
  tmp-data:
  log-data:
  db-data:

networks:
  boardgame_match-network:
    external: true